### ISSUE TITLE
Extracting Spacer Alignment

### ISSUE THREAD

**Issue by rfroumine** [CRISPRlab/CRISPRviz#2]
I would really like to extract the final multiple sequence alignment of spacers from the web app. 
I have been looking at the [multipleSeqAlignment.js](https://github.com/CRISPRlab/CRISPRviz/blob/master/app/multipleSeqAlignment.js) script but I am not very experienced in java script. Would you be able to direct me to the right point in the script where I can do this. Thank you

**Comment by mnethery** [comment]
Hi rfroumine, the object you're looking for is the **spacerOutput** object in **main.js**:
var spacerOutput = {};

What type of alignment format were you thinking about using?

**Comment by rfroumine** [comment]
Hi mnethery, thanks for your reply. 
I was looking for the integer alignment (after the nucleotide sequence of each spacer has been converted into an integer).
I'd also like to confirm that I've understood the approach correctly: that every unique colour/ symbol combination represents a unique spacer sequence, such that even a pair of sequences with only 1 mismatch would be represented differently? Thank you!

**Comment by mnethery** [comment]
Hi rfroumine,

Your understanding of the approach is correct. In this tool, we want to see
even a single-nucleotide mismatch represented differently. This is helpful
for many reasons: one example and common use is in determining locus
orientation using SNPs in the terminal repeat.

Thank you!

**Comment by rfroumine** [comment]
Hi mnethery. 
Thank you for the explanation. 
Roni
