### ISSUE TITLE
Counts and types of CRISPR?

### ISSUE THREAD

**Issue by yjiakang** [CRISPRlab/CRISPRviz#3]
Hello
Thanks for your wonderful tool, I am little confused that how can I get the counts and types of CRISPR in my genome. Just mannually count according to the web-based graph?
Thanks in advance.

**Comment by mnethery** [comment]
Hello, 
To get the number of CRISPR loci, you can count the number of _.crisprs_ files in the directory where you ran crisprviz.sh. On the command line, you can use something like: 
_find . -maxdepth 1 -name "*.crisprs" | wc -l_

To determine the types of each system you need information about the cas genes, so you need to use a classification tool like CRISPRdisco (https://github.com/CRISPRlab/CRISPRdisco), which output information about each strain's type.
