### ISSUE TITLE
downloading CRISPR visuals

### ISSUE THREAD

**Issue by vmkhot** [CRISPRlab/CRISPRviz#4]
Hi there, thanks so much for the easy-to-use visualization tool! I'm wondering if there's a way to download the visuals of the CRISPR arrays from the interactive session on the browser? The only option I saw was to download as a JSON file - am I missing something? Thanks, Varada

**Comment by mnethery** [comment]
Hi Varada, 

Thanks for using our tool! This is a feature we've been asked about frequently, so we decided to go ahead and release it. If you git pull the latest version, you will now see a 'Screenshot' item in the drop down menu that will download a .png screenshot of the results. Let us know if you have any questions!

-CRISPRlab

**Comment by vmkhot** [comment]
Hi there,

Thanks for the update! I've tried several times to rerun CRISPRViz after pulling the latest version. I believe the program runs fine because I do get a spacerOutput.json file but it no longer sends anything to my localhost. I'm running the program on a server so I have to use an IP address to see the results on my browser and have checked that these are correct. 
I also tried wget http://IPaddress:4444/ and it says no data received. I'm wondering if there's an issue with the data being sent to localhost or something that I can try on my end? 
Thanks again, Varada

**Comment by mnethery** [comment]
Hi Varada,

Sometimes when updating, processes from the old version are still running
(server.py) and can conflict with the newer version, so try totally killing
the old threads on the server first:
ps -ax | grep python
and search for the CRISPRviz process, then kill it (kill xxxx).
I would also delete any files within the CRISPRviz/data directory just to
be sure a new spacerOutput.json is being generated.

Are you getting a 404 Page not found when trying to access
http://IPaddress:4444?

Matt

**Comment by vmkhot** [comment]
That worked amazingly and I can take a screenshot now! 

Thank you so much for all your help!

Varada

**Comment by mnethery** [comment]
That's great! We hope this helps your research! Best of luck.

Matt
